### ISSUE TITLE
Scanner function

### ISSUE THREAD

**Issue by mdjohns** [mdjohns/cpp-parser#1]
Create a scanner function that receives a string of input, checks for valid tokens, and returns an array of the valid tokens.

**Comment by mdjohns** [comment]
The scanner is mostly functional, but it needs some work. 

The function needs to be modified to look for multi character words. Currently, `11 + 22 = 33` would return `['1','1','+','2','2','=','3','3']` instead of `['11','+','22','=','33']`.

I'll be tinkering this weekend, but feel free to jump in.

**Comment by ashjornew** [comment]
Have you tried having it convert to a string so it can read more than one digit at a time?

**Comment by mdjohns** [comment]
I just pushed an update and I think it covers all cases. I tested for floating point, integers with multiple digits, strings, etc. Let me know if you see anything weird.

**Comment by mdjohns** [comment]
Scanner function has been updated. Looks like it *mostly* works, still need to test for edge cases.

Main concern now is that the scanner doesn't want to recognize semicolons when they are against another character.
Ex.
```cpp
if (1 > 2) {
  return true;
}
```

When scanned, the semicolon doesn't get picked up as a separate token by the parser. I believe it's an issue with isDigit or isLetter in the scanner() function. Let's investigate.

**Comment by mdjohns** [comment]
I believe the semicolon issue has been corrected now by adding a lookahead in the `isDigit` and `isLetter` functions.

**Comment by mdjohns** [comment]
Completed! 👻
